SET SERVEROUTPUT ON;

-- Exercício 1 --
 
DECLARE

    QNT_MOVIMENTACAO NUMBER;

    PRODUTO NUMBER;

BEGIN

    PRODUTO := &PRODUTO;

    SELECT SUM(QTD_MOVIMENTACAO_ESTOQUE)

    INTO QNT_MOVIMENTACAO

    FROM MOVIMENTO_ESTOQUE

    WHERE COD_PRODUTO = PRODUTO;

     DBMS_OUTPUT.PUT_LINE('A QUANTIDADE DE MOVIMENTAÇÕES DE ESTOQUE DO PRODUTO ' || PRODUTO || 

     ' É IGUAL A ' || QNT_MOVIMENTACAO);

END;

-- Exercício 2 --

DECLARE
    QNT_PEDIDOS NUMBER := 0;
    SOMA_PEDIDOS NUMBER := 0;
    CLIENTE NUMBER;
BEGIN
    CLIENTE := &CLIENTE;

    FOR PEDIDO IN (SELECT VAL_TOTAL_PEDIDO FROM PEDIDO WHERE COD_CLIENTE = CLIENTE) LOOP
        QNT_PEDIDOS := QNT_PEDIDOS + 1;
        SOMA_PEDIDOS := SOMA_PEDIDOS + PEDIDO.VAL_TOTAL_PEDIDO;
    END LOOP;

    IF QNT_PEDIDOS > 0 THEN
        DBMS_OUTPUT.PUT_LINE('A MÉDIA DOS VALORES DO PEDIDO DO CLIENTE ' || CLIENTE || 
                             ' É IGUAL A ' || ROUND(SOMA_PEDIDOS / QNT_PEDIDOS, 2));
    ELSE
        DBMS_OUTPUT.PUT_LINE('O CLIENTE ' || CLIENTE || ' NÃO POSSUI PEDIDOS.');
    END IF;
END;

-- Exercício 3 --

BEGIN
    FOR PRODUTOS IN (
        SELECT DISTINCT PROD.NOM_PRODUTO
        FROM PRODUTO_COMPOSTO COMPO
        INNER JOIN PRODUTO PROD
            ON COMPO.COD_PRODUTO = PROD.COD_PRODUTO
        WHERE COMPO.STA_ATIVO = 'S'
    ) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('Produto composto ativo: ' || PRODUTOS.NOM_PRODUTO);
    END LOOP;
END;

-- Exercício 4 --

DECLARE
    PRODUTO NUMBER;
    TOTAL_ENTRADAS NUMBER := 0;
    TOTAL_SAIDAS NUMBER := 0;
BEGIN
    PRODUTO := &PRODUTO;
    FOR REGISTRO IN (
        SELECT TIPO.DES_TIPO_MOVIMENTO_ESTOQUE, 
            SUM(MOV.QTD_MOVIMENTACAO_ESTOQUE) AS TOTAL
        FROM MOVIMENTO_ESTOQUE MOV
        INNER JOIN TIPO_MOVIMENTO_ESTOQUE TIPO 
            ON MOV.COD_TIPO_MOVIMENTO_ESTOQUE = TIPO.COD_TIPO_MOVIMENTO_ESTOQUE
        WHERE MOV.COD_PRODUTO = PRODUTO
        GROUP BY TIPO.DES_TIPO_MOVIMENTO_ESTOQUE
    ) LOOP
        IF REGISTRO.DES_TIPO_MOVIMENTO_ESTOQUE = 'Entrada' THEN
            TOTAL_ENTRADAS := REGISTRO.TOTAL;
        ELSIF REGISTRO.DES_TIPO_MOVIMENTO_ESTOQUE = 'Saída' THEN
            TOTAL_SAIDAS := REGISTRO.TOTAL;
        END IF;
    END LOOP;

    -- Exibir resultados
    DBMS_OUTPUT.PUT_LINE('Produto: ' || PRODUTO);
    DBMS_OUTPUT.PUT_LINE('Total de Movimentacoes: ' || (TOTAL_ENTRADAS + TOTAL_SAIDAS));
    DBMS_OUTPUT.PUT_LINE('Total de Entradas: ' || TOTAL_ENTRADAS);
    DBMS_OUTPUT.PUT_LINE('Total de Saídas: ' || TOTAL_SAIDAS);
END;
    
-- Exercício 5 --
    
BEGIN
    FOR PRODUTO_ESTOQUE IN (
        SELECT COMPO.COD_PRODUTO, SUM(NVL(EST.QTD_PRODUTO, 0)) AS TOTAL_ESTOQUE
        FROM PRODUTO_COMPOSTO COMPO
        LEFT JOIN ESTOQUE_PRODUTO EST
            ON COMPO.COD_PRODUTO = EST.COD_PRODUTO
        GROUP BY COMPO.COD_PRODUTO
    ) LOOP
    
        DBMS_OUTPUT.PUT_LINE('Produto: ' || PRODUTO_ESTOQUE.COD_PRODUTO || 
        ' ESTOQUE: ' || PRODUTO_ESTOQUE.TOTAL_ESTOQUE);
    
    END LOOP;
END;

-- Exercicio 6 --

BEGIN
    FOR INFO_PEDIDOS IN (
        SELECT CLI.NOM_CLIENTE, CLI.NUM_CPF_CNPJ, 
        PED.COD_PEDIDO, ped.val_total_pedido, ped.cod_vendedor, ped.status
        FROM PEDIDO PED
        RIGHT JOIN CLIENTE CLI
            ON PED.COD_CLIENTE = CLI.COD_CLIENTE
    ) LOOP
    
        DBMS_OUTPUT.PUT_LINE('PEDIDO: ' || INFO_PEDIDOS.COD_PEDIDO 
        || ' STATUS: ' || INFO_PEDIDOS.status
        || ' VALOR FINAL: ' || INFO_PEDIDOS.val_total_pedido
        || ' VENDEDOR: ' || INFO_PEDIDOS.cod_vendedor
        || ' CLIENTE: ' || INFO_PEDIDOS.NOM_CLIENTE
        || ' CNP/CNPJ DO CLIENTE: ' || INFO_PEDIDOS.NUM_CPF_CNPJ);
    
    END LOOP;
END;

-- Exercício 7 --

DECLARE

CLIENTE NUMBER;

BEGIN

    CLIENTE := &CLIENTE;

    FOR CLIENTE_INFO IN (
        SELECT SUM(PED.VAL_TOTAL_PEDIDO) AS SOMA_VALOR,
        COUNT(PED.VAL_TOTAL_PEDIDO) AS QNT_VALOR,
        CLI.NOM_CLIENTE, CLI.NUM_CPF_CNPJ
        FROM PEDIDO PED
        INNER JOIN CLIENTE CLI
            ON CLI.COD_CLIENTE = PED.COD_CLIENTE 
        WHERE PED.COD_CLIENTE = CLIENTE
        group by CLI.NOM_CLIENTE, CLI.NUM_CPF_CNPJ
        
    ) LOOP
    IF CLIENTE_INFO.QNT_VALOR > 0 THEN
            DBMS_OUTPUT.PUT_LINE('CLIENTE: ' || CLIENTE_INFO.NOM_CLIENTE);
            DBMS_OUTPUT.PUT_LINE('CPF/CNPJ DO CLIENTE: ' || CLIENTE_INFO.NUM_CPF_CNPJ);
            DBMS_OUTPUT.PUT_LINE('QUANTIDADE DE PEDIDOS ' || CLIENTE_INFO.QNT_VALOR);
            DBMS_OUTPUT.PUT_LINE('SOMA DOS PEDIDOS ' || CLIENTE_INFO.SOMA_VALOR);
            DBMS_OUTPUT.PUT_LINE('MÉDIA DOS VALORES: '|| ROUND(CLIENTE_INFO.SOMA_VALOR / CLIENTE_INFO.QNT_VALOR, 2));
        ELSE
            DBMS_OUTPUT.PUT_LINE('CLIENTE: ' || CLIENTE_INFO.NOM_CLIENTE);
            DBMS_OUTPUT.PUT_LINE('CPF/CNPJ DO CLIENTE: ' || CLIENTE_INFO.NUM_CPF_CNPJ);
            DBMS_OUTPUT.PUT_LINE(' NÃO POSSUI PEDIDOS REGISTRADOS.');
        END IF;
    END LOOP;
END;
    
    
    
    
    
 